UPDATE CUSTOMERS SET EMAIL = 'carolina@campuscode.com.br', WHERE EMAIL = 'carol@ig.com.br';

SELECT * FROM CUSTOMERS;

UPDATE CUSTOMERS SET BIRTH_DATE = '1986-06-19' WHERE NAME = 'Josefa';

SELECT * FROM CUSTOMERS WHERE NAME = 'Josefa';

UPDATE CARS SET YEAR = '2019' WHERE NAME = 'Fiat Cronos'; 
SELECT * FROM CARS;

SELECT * FROM CARS WHERE NAME = 'Fiat Cronos';

DELETE FROM CARS WHERE NAME = 'Hyundai HB20 1.6';

SELECT * FROM CARS;

ALTER TABLE EMPLOYEES
RENAME COLUMN 'PHONE' TO 'PHONE NUMBER';

SELECT * FROM EMPLOYEES;