SELECT L.ID AS 'Código', L.START_DATE AS 'Início', L.END_DATE AS 'Final', L.TOTAL AS 'Total', C.NAME AS 'Clinte', A.NAME AS 'Carro', E.NAME AS 'Funcionário' FROM LOCATIONS AS L

  INNER JOIN CUSTOMERS AS C ON (L.CUSTOMER_ID = C.ID)
  INNER JOIN CARS AS A ON (L.CAR_ID = A.ID)
  INNER JOIN EMPLOYEES AS E ON (L.EMPLOYEE_ID = E.ID)

SELECT COUNT(ID) AS 'Total de locações' FROM LOCATIONS 

SELECT L.ID AS 'Código', L.START_DATE AS 'Início', L.END_DATE AS 'Final', MAX(TOTAL) AS 'Maior Locação', C.NAME AS 'Clinte', A.NAME AS 'Carro', E.NAME AS 'Funcionário' FROM LOCATIONS AS L

  INNER JOIN CUSTOMERS AS C ON (L.CUSTOMER_ID = C.ID)
  INNER JOIN CARS AS A ON (L.CAR_ID = A.ID)
  INNER JOIN EMPLOYEES AS E ON (L.EMPLOYEE_ID = E.ID)


SELECT L.ID AS 'Código', L.START_DATE AS 'Início', L.END_DATE AS 'Final', L.TOTAL AS 'Total' , C.NAME AS 'Clinte', A.NAME AS 'Carro', E.NAME AS 'Funcionário' FROM LOCATIONS AS L

  INNER JOIN CUSTOMERS AS C ON (L.CUSTOMER_ID = C.ID)
  INNER JOIN CARS AS A ON (L.CAR_ID = A.ID)
  INNER JOIN EMPLOYEES AS E ON (L.EMPLOYEE_ID = E.ID)

WHERE L.START_DATE >= '2022-05-20' AND L.END_DATE <= '2022-12-25';